name = "rubeus"
compatibility_date = "2024-12-05"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]

[vars]
ENVIRONMENT = 'dev'
CUSTOM_HEADERS_TO_IGNORE = []
DATABASE_URL = 'postgresql://postgres:fti123@34.124.178.40:5432/onporta'
JWT_SECRET = 'fti123'
JWT_EXPIRES_IN = '14d'

#
#Configuration for DEVELOPMENT environment
#
[env.staging]
name = "rubeus-dev"

[env.staging.vars]
ENVIRONMENT = 'staging'
CUSTOM_HEADERS_TO_IGNORE = []
DATABASE_URL = 'postgresql://postgres:fti123@34.124.178.40:5432/onporta'
JWT_SECRET = 'fti123'
JWT_EXPIRES_IN = '14d'


#
#Configuration for PRODUCTION environment
#
[env.production]
name = "rubeus"
logpush=true

[env.production.vars]
ENVIRONMENT = 'production'
CUSTOM_HEADERS_TO_IGNORE = []
DATABASE_URL = 'postgresql://postgres:fti123@34.124.178.40:5432/onporta'
JWT_SECRET = 'fti123-production'
JWT_EXPIRES_IN = '14d'
